global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js application instances
  - job_name: 'nodejs-backend'
    static_configs:
      - targets: 
        - 'backend-1:3001'
        - 'backend-2:3002'
        - 'backend-3:3003'
        - 'backend-4:3004'
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 5s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 5s

  # MongoDB metrics (if mongodb_exporter is used)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:9216']
    scrape_interval: 5s